-- schema_oracle.sql
-- Criação das tabelas principais

CREATE TABLE sensors (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR2(60)   NOT NULL,
  location   VARCHAR2(120),
  created_at TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE TABLE readings (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id     NUMBER       NOT NULL,
  recorded_at   TIMESTAMP    NOT NULL,
  temperature_c NUMBER(5,2)  NOT NULL,
  humidity_pct  NUMBER(5,2)  NOT NULL,
  CONSTRAINT fk_readings_sensor FOREIGN KEY (sensor_id) REFERENCES sensors(id),
  CONSTRAINT chk_humidity_range CHECK (humidity_pct BETWEEN 0 AND 100)
);

-- Evita leituras duplicadas no mesmo instante para o mesmo sensor
ALTER TABLE readings
  ADD CONSTRAINT uq_readings_unique_moment
  UNIQUE (sensor_id, recorded_at);

-- Índice para consultas rápidas
CREATE INDEX idx_readings_sensor_time
  ON readings (sensor_id, recorded_at);
