-- Sensores de exemplo
INSERT INTO sensors (name, location) VALUES ('DHT22-Lab',    'Corredor A');
INSERT INTO sensors (name, location) VALUES ('DHT22-Sala1',  'Sala 101');
INSERT INTO sensors (name, location) VALUES ('DHT22-Externo','Área Técnica');
COMMIT;

-- Leituras de exemplo (5 por sensor)
BEGIN
  INSERT INTO readings VALUES (DEFAULT, 1, SYSTIMESTAMP - INTERVAL '4' MINUTE, 24.5, 50.2);
  INSERT INTO readings VALUES (DEFAULT, 1, SYSTIMESTAMP - INTERVAL '3' MINUTE, 25.1, 47.8);
  INSERT INTO readings VALUES (DEFAULT, 1, SYSTIMESTAMP - INTERVAL '2' MINUTE, 23.9, 55.0);
  INSERT INTO readings VALUES (DEFAULT, 1, SYSTIMESTAMP - INTERVAL '1' MINUTE, 26.3, 42.4);
  INSERT INTO readings VALUES (DEFAULT, 1, SYSTIMESTAMP, 24.8, 48.6);

  INSERT INTO readings VALUES (DEFAULT, 2, SYSTIMESTAMP - INTERVAL '4' MINUTE, 22.4, 57.1);
  INSERT INTO readings VALUES (DEFAULT, 2, SYSTIMESTAMP - INTERVAL '3' MINUTE, 23.1, 53.3);
  INSERT INTO readings VALUES (DEFAULT, 2, SYSTIMESTAMP - INTERVAL '2' MINUTE, 25.6, 44.9);
  INSERT INTO readings VALUES (DEFAULT, 2, SYSTIMESTAMP - INTERVAL '1' MINUTE, 24.2, 46.7);
  INSERT INTO readings VALUES (DEFAULT, 2, SYSTIMESTAMP, 23.8, 49.5);

  INSERT INTO readings VALUES (DEFAULT, 3, SYSTIMESTAMP - INTERVAL '4' MINUTE, 26.1, 41.8);
  INSERT INTO readings VALUES (DEFAULT, 3, SYSTIMESTAMP - INTERVAL '3' MINUTE, 25.4, 43.2);
  INSERT INTO readings VALUES (DEFAULT, 3, SYSTIMESTAMP - INTERVAL '2' MINUTE, 24.9, 45.6);
  INSERT INTO readings VALUES (DEFAULT, 3, SYSTIMESTAMP - INTERVAL '1' MINUTE, 25.7, 47.3);
  INSERT INTO readings VALUES (DEFAULT, 3, SYSTIMESTAMP, 24.6, 50.1);
  COMMIT;
END;
/
